### ISSUE TITLE
Protect Demo Workflow

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/GateKeeperSampleApp#17]
At no time should a User be able to Enroll with a captured Template without having the Demo Template already on the Card.

Given I want to Authenticate
And I am not enrolled
When I open the app
Then I should be able to enroll

Given I want to Authenticate
And I am enrolled
When I open the app
Then I should be able to authenticate

Given I want to Authenticate
And I am enrolled with a different biometric
When I get in the app
Then I should be able to remove the Biometric

Given I want to Authenticate
And I am/not enrolled
When I click bypass
Then I should be able to enter the app normally

**Comment by jneander** [comment]
Released with 791489fe92918015ad441981525a85f978536a16.
