### ISSUE TITLE
Unify Dialog Fragments

### ISSUE THREAD

**Issue by jneander** [BluStor/GateKeeperSampleApp#29]
* [ ] Handle Outside Touch (when allowed)
* [ ] Preserve During Rotation
* [ ] Prevent Dismiss (when not allowed)
* [ ] Move to 'dialogs' Package

**Comment by bravozulu1** [comment]
I think this issue is not needed? The goals is to complete the demo and only resolve critical issues. If no response is provided, I will cancel the ticket.

**Comment by bravozulu1** [comment]
Closing, not needed
